#!/usr/bin/env python3
"""Resize firmware/assets/red_scale_logo.png and emit red_scale_logo_bitmap.h for Adafruit_GFX."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def classify_pixel(r: int, g: int, b: int, a: int) -> tuple[bool, bool]:
    """Split into black vs red ink for B/W/R panel. Red hue wins over dark neutrals."""
    if a < 128:
        return False, False
    L = 0.299 * r + 0.587 * g + 0.114 * b
    if L > 252:
        return False, False

    ex_red = r - max(g, b)
    max_rgb = max(r, g, b)
    min_rgb = min(r, g, b)
    sat = (max_rgb - min_rgb) / max(max_rgb, 1)
    is_neutral = sat < 0.14

    # Marker / "RED" / small red year: R leads G and B (including darker fills).
    red_ink = ex_red > 6 and r > 38 and L < 252

    # Grays, black outlines, "SCALE" fill — no dominant red channel.
    black_ink = False
    if is_neutral and L < 248:
        black_ink = L < 245
    elif not red_ink and L < 250:
        black_ink = True
    elif ex_red <= 4 and L < 235:
        black_ink = True

    red = red_ink
    black = black_ink
    # Dark fringe on red strokes: near-black wins (outline).
    if black and red:
        if L < 55 and ex_red < 18:
            red = False
        elif ex_red >= 14:
            black = False
        else:
            red = False
    return black, red


def pack_bitmap(pixels: list[bool], w: int, h: int) -> bytes:
    out = bytearray()
    byte_w = (w + 7) // 8
    for y in range(h):
        for bx in range(byte_w):
            v = 0
            for bi in range(8):
                x = bx * 8 + bi
                if x < w and pixels[y * w + x]:
                    v |= 128 >> bi
            out.append(v)
    return bytes(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--png",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "firmware/assets/red_scale_logo.png",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "firmware/src/red_scale_logo_bitmap.h",
    )
    ap.add_argument("--max-w", type=int, default=200)
    ap.add_argument("--max-h", type=int, default=150)
    ap.add_argument(
        "--width-scale",
        type=float,
        default=1.5,
        help="Multiply fitted width/height by this (default 1.5 for larger logo).",
    )
    args = ap.parse_args()

    try:
        from PIL import Image
    except ImportError:
        print("Need Pillow: pip install Pillow", file=sys.stderr)
        return 1

    im = Image.open(args.png).convert("RGBA")
    iw, ih = im.size
    scale = min(args.max_w / iw, args.max_h / ih, 1.0)
    nw = max(1, int(round(iw * scale)))
    nh = max(1, int(round(ih * scale)))
    if args.width_scale != 1.0:
        nw = max(1, int(round(nw * args.width_scale)))
        nh = max(1, int(round(nh * args.width_scale)))
    im = im.resize((nw, nh), Image.Resampling.LANCZOS)

    black_bits: list[bool] = []
    red_bits: list[bool] = []
    for y in range(nh):
        for x in range(nw):
            r, g, b, a = im.getpixel((x, y))
            bl, rd = classify_pixel(r, g, b, a)
            black_bits.append(bl)
            red_bits.append(rd)

    bb = pack_bitmap(black_bits, nw, nh)
    rb = pack_bitmap(red_bits, nw, nh)
    byte_w = (nw + 7) // 8

    def c_array(data: bytes) -> str:
        lines: list[str] = []
        row = []
        for i, b in enumerate(data):
            row.append(f"0x{b:02X}")
            if len(row) >= 16:
                lines.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ", ".join(row) + ",")
        return "\n".join(lines)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    body = f"""#pragma once
// Generated by tools/gen_red_scale_logo.py from firmware/assets/red_scale_logo.png
// Adafruit_GFX drawBitmap: row-major, MSB=left, 1=ink

#include <Arduino.h>

static constexpr int kRedScaleLogoW = {nw};
static constexpr int kRedScaleLogoH = {nh};
static constexpr int kRedScaleLogoBytesPerRow = {byte_w};

static const uint8_t kRedScaleLogoBlack[] PROGMEM = {{
{c_array(bb)}
}};

static const uint8_t kRedScaleLogoRed[] PROGMEM = {{
{c_array(rb)}
}};
"""
    args.out.write_text(body, encoding="utf-8")
    print(f"Wrote {args.out} ({nw}x{nh}, {len(bb)} bytes/plane)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
