#!/usr/bin/env python3
"""
One-shot OAuth for Google Calendar (readonly): opens the consent URL, receives the
authorization code on localhost, exchanges it for tokens, and writes firmware/src/google_secrets.h.

Requires a Google Cloud OAuth client (Desktop app). Add this exact redirect URI to the client:
  http://127.0.0.1:<port>/
Default port is 8085 (see --port).

Uses only the Python standard library.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
import webbrowser
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

SCOPE = "https://www.googleapis.com/auth/calendar.readonly"
TOKEN_URL = "https://oauth2.googleapis.com/token"
AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"


def c_define_escape(s: str) -> str:
    """Escape a string for use inside C double-quoted string literals."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def parse_existing_client_credentials(path: Path) -> tuple[str | None, str | None]:
    """Read GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET from an existing header."""
    if not path.is_file():
        return None, None
    text = path.read_text(encoding="utf-8")
    cid = None
    sec = None
    m = re.search(r'^\s*#define\s+GOOGLE_CLIENT_ID\s+"([^"]*)"\s*$', text, re.M)
    if m:
        cid = m.group(1).encode("utf-8").decode("unicode_escape")
    m = re.search(r'^\s*#define\s+GOOGLE_CLIENT_SECRET\s+"([^"]*)"\s*$', text, re.M)
    if m:
        sec = m.group(1).encode("utf-8").decode("unicode_escape")
    return cid, sec


def build_auth_url(client_id: str, redirect_uri: str) -> str:
    q = urllib.parse.urlencode(
        {
            "client_id": client_id,
            "redirect_uri": redirect_uri,
            "response_type": "code",
            "scope": SCOPE,
            "access_type": "offline",
            "prompt": "consent",
        }
    )
    return f"{AUTH_URL}?{q}"


def exchange_code(
    code: str,
    client_id: str,
    client_secret: str,
    redirect_uri: str,
) -> dict:
    body = urllib.parse.urlencode(
        {
            "code": code,
            "client_id": client_id,
            "client_secret": client_secret,
            "redirect_uri": redirect_uri,
            "grant_type": "authorization_code",
        }
    ).encode("utf-8")
    req = urllib.request.Request(
        TOKEN_URL,
        data=body,
        method="POST",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read().decode("utf-8"))


def write_secrets_header(
    out_path: Path,
    client_id: str,
    client_secret: str,
    refresh_token: str,
) -> None:
    lines = [
        "// Generated by tools/google_oauth_setup.py — keep out of git.",
        "// Re-run the tool if the refresh token stops working.",
        "",
        "#pragma once",
        "",
        f'#define GOOGLE_CLIENT_ID "{c_define_escape(client_id)}"',
        f'#define GOOGLE_CLIENT_SECRET "{c_define_escape(client_secret)}"',
        f'#define GOOGLE_REFRESH_TOKEN "{c_define_escape(refresh_token)}"',
        "",
    ]
    text = "\n".join(lines)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = out_path.with_suffix(out_path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(out_path)


def run_callback_server(port: int) -> tuple[str | None, str | None]:
    """Wait for one GET with ?code= or ?error=. Returns (code, error)."""
    result: dict[str, str | None] = {"code": None, "error": None}

    class Handler(BaseHTTPRequestHandler):
        def log_message(self, fmt: str, *args: object) -> None:
            return

        def do_GET(self) -> None:  # noqa: N802
            parsed = urllib.parse.urlparse(self.path)
            qs = urllib.parse.parse_qs(parsed.query)
            if "code" not in qs and "error" not in qs:
                self.send_response(404)
                self.end_headers()
                return
            if "code" in qs:
                result["code"] = qs["code"][0]
            if "error" in qs:
                result["error"] = qs["error"][0]
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.end_headers()
            if result.get("error"):
                msg = urllib.parse.quote(result["error"] or "", safe="")
                body = (
                    f"<html><body><p>Authorization failed: {msg}</p>"
                    "<p>You can close this tab.</p></body></html>"
                )
            else:
                body = (
                    "<html><body><p>Authorization received. You can close this tab "
                    "and return to the terminal.</p></body></html>"
                )
            self.wfile.write(body.encode("utf-8"))

    server = HTTPServer(("127.0.0.1", port), Handler)
    try:
        while result["code"] is None and result["error"] is None:
            server.handle_request()
    finally:
        server.server_close()

    return result["code"], result["error"]


def main() -> int:
    p = argparse.ArgumentParser(
        description="OAuth consent + write firmware Google secrets header."
    )
    p.add_argument(
        "--client-id",
        help="OAuth client ID (or set GOOGLE_CLIENT_ID)",
        default=None,
    )
    p.add_argument(
        "--client-secret",
        help="OAuth client secret (or set GOOGLE_CLIENT_SECRET)",
        default=None,
    )
    p.add_argument(
        "--from-file",
        type=Path,
        metavar="PATH",
        help="Read client id/secret from this header if not passed on CLI",
    )
    p.add_argument(
        "--output",
        "-o",
        type=Path,
        default=Path("firmware/src/google_secrets.h"),
        help="Output header path (default: firmware/src/google_secrets.h)",
    )
    p.add_argument(
        "--port",
        type=int,
        default=8085,
        help="Local callback port (default: 8085)",
    )
    p.add_argument(
        "--no-browser",
        action="store_true",
        help="Print the consent URL instead of opening a browser",
    )
    args = p.parse_args()

    import os

    client_id = args.client_id or os.environ.get("GOOGLE_CLIENT_ID")
    client_secret = args.client_secret or os.environ.get("GOOGLE_CLIENT_SECRET")

    from_path = args.from_file
    if from_path is None:
        from_path = Path("firmware/src/google_secrets.h")
    if not client_id or not client_secret:
        f_id, f_sec = parse_existing_client_credentials(from_path)
        client_id = client_id or f_id
        client_secret = client_secret or f_sec

    if not client_id or not client_secret:
        print(
            "Missing client id/secret. Pass --client-id and --client-secret, "
            "set GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET, or use a --from-file "
            "header that already defines them.",
            file=sys.stderr,
        )
        return 1

    redirect_uri = f"http://127.0.0.1:{args.port}/"
    auth_url = build_auth_url(client_id, redirect_uri)

    print("Add this Authorized redirect URI to your OAuth client (Desktop) if prompted:")
    print(f"  {redirect_uri}")
    print()
    print("Consent URL:")
    print(auth_url)
    print()

    if not args.no_browser:
        webbrowser.open(auth_url)

    print(f"Waiting for redirect on {redirect_uri} ...")
    code, oauth_err = run_callback_server(args.port)
    if oauth_err:
        print(f"OAuth error: {oauth_err}", file=sys.stderr)
        return 1
    if not code:
        print("No authorization code received.", file=sys.stderr)
        return 1

    try:
        token_payload = exchange_code(code, client_id, client_secret, redirect_uri)
    except urllib.error.HTTPError as e:
        err_body = e.read().decode("utf-8", errors="replace")
        print(f"Token exchange HTTP {e.code}: {err_body}", file=sys.stderr)
        return 1
    except urllib.error.URLError as e:
        print(f"Token exchange failed: {e}", file=sys.stderr)
        return 1

    refresh = token_payload.get("refresh_token")
    if not refresh:
        print(
            "No refresh_token in response. Try revoking app access in Google Account "
            "→ Security → Third-party access, then run again with --no-browser if "
            "needed; ensure prompt=consent is used (this script does). Response:",
            json.dumps(token_payload, indent=2),
            file=sys.stderr,
        )
        return 1

    write_secrets_header(args.output, client_id, client_secret, refresh)
    print(f"Wrote {args.output.resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
